from __future__ import annotations

from app.schemas import SourceCatalogEntry


DEFAULT_SOURCE_CATALOG = [
    SourceCatalogEntry(
        title="Instructions for Form 1040 and 1040-SR",
        source_url="https://www.irs.gov/instructions/i1040gi",
        source_type="forms_instructions",
        authority_type="irs_form_instructions",
        authority_tier=1,
        priority_order=1,
        topic_tags=["form-1040", "individual", "standard-deduction"],
        tax_year=2025,
        form_number="1040",
        scope_tag="standard-deduction",
    ),
    SourceCatalogEntry(
        title="Publication 17, Your Federal Income Tax",
        source_url="https://www.irs.gov/publications/p17",
        source_type="publication",
        authority_type="irs_publication",
        authority_tier=1,
        priority_order=2,
        topic_tags=["individual", "withholding", "filing-basics"],
        publication_number="17",
        tax_year=2025,
        scope_tag="withholding",
    ),
    SourceCatalogEntry(
        title="Publication 970, Tax Benefits for Education",
        source_url="https://www.irs.gov/publications/p970",
        source_type="publication",
        authority_type="irs_publication",
        authority_tier=1,
        priority_order=2,
        topic_tags=["education", "credits", "1098-t"],
        publication_number="970",
        tax_year=2025,
        scope_tag="education",
    ),
    SourceCatalogEntry(
        title="QuickAlerts library",
        source_url="https://www.irs.gov/e-file-providers/quickalerts-library",
        source_type="quickalerts",
        authority_type="irs_quickalerts",
        authority_tier=1,
        priority_order=3,
        topic_tags=["quickalerts", "alerts", "mef", "iris"],
        scope_tag="quickalerts",
    ),
    SourceCatalogEntry(
        title="Modernized e-File (MeF) user guides and publications",
        source_url="https://www.irs.gov/e-file-providers/modernized-e-file-mef-user-guides-and-publications",
        source_type="mef_guidance",
        authority_type="irs_software_developer_guidance",
        authority_tier=1,
        priority_order=3,
        topic_tags=["mef", "developer-guidance", "schemas", "publications"],
        scope_tag="mef",
    ),
    SourceCatalogEntry(
        title="E-file information returns with IRIS",
        source_url="https://www.irs.gov/filing/e-file-information-returns-with-iris",
        source_type="iris_guidance",
        authority_type="irs_iris_guidance",
        authority_tier=1,
        priority_order=3,
        topic_tags=["iris", "a2a", "1099", "information-returns"],
        scope_tag="iris-a2a",
    ),
    SourceCatalogEntry(
        title="IRIS schemas and business rules",
        source_url="https://www.irs.gov/e-file-providers/iris-schemas-and-business-rules",
        source_type="iris_business_rules",
        authority_type="irs_iris_guidance",
        authority_tier=1,
        priority_order=3,
        topic_tags=["iris", "schemas", "business-rules"],
        scope_tag="iris-a2a",
    ),
    SourceCatalogEntry(
        title="Taxpayer Identification Number (TIN) Matching",
        source_url="https://www.irs.gov/tax-professionals/taxpayer-identification-number-tin-matching",
        source_type="tin_matching",
        authority_type="irs_tax_professional_guidance",
        authority_tier=1,
        priority_order=4,
        topic_tags=["tin-matching", "e-services", "information-returns"],
        scope_tag="tin-matching",
    ),
    SourceCatalogEntry(
        title="Transcript Delivery System (TDS)",
        source_url="https://www.irs.gov/tax-professionals/transcript-delivery-system-tds",
        source_type="transcript_workflow",
        authority_type="irs_tax_professional_guidance",
        authority_tier=1,
        priority_order=4,
        topic_tags=["transcripts", "tds", "workflow"],
        scope_tag="transcript-workflow",
    ),
]
